### ISSUE TITLE
TypeError: Cannot read property 'nodeName' of null

### ISSUE THREAD

**Issue by mparpaillon** [mzgoddard/preact-render-spy#10]
Hi,
Thanks for this. It looks cool.

I get this `TypeError: Cannot read property 'nodeName' of null` error though. I haven't looked at all the code yet but it looks like you're recursively checking the vdom and at some point you try to check the nodeName of `null`

I think we should add a test on vdom being `null` here: https://github.com/mzgoddard/preact-render-spy/blob/master/src/preact-render-spy.js#L10

It seems to work when I add this at the beginning of `spyWalk`:
```js
if (vdom === null) {
  return '';
}
```

Does it make sense ?

**Comment by mparpaillon** [comment]
Same problem here: https://github.com/mzgoddard/preact-render-spy/blob/master/src/preact-render-spy.js#L112

Am I using this wrong ?

**Comment by gnarf** [comment]
No, I just don't think we had a test case for `<div>{[ null, <div /> ]}</div>` type scenario yet.

I'll add a test case real quick

**Comment by gnarf** [comment]
#11 should fix the problem, just waiting for the travis to pass!

**Comment by gnarf** [comment]
Thanks for catching this one!

Let us know if there are other test cases that fail (feel free to write a failing test case for us! 😄 )

**Comment by mparpaillon** [comment]
Have you `npm publish` the package ? Or should I install from the github url ?

**Comment by gnarf** [comment]
Sorry I didn't publish it. Maybe Z will today

**Comment by mparpaillon** [comment]
It's OK, I've installed it from github. Works fine :)

**Comment by mzgoddard** [comment]
@mparpaillon I published the fix in `v0.0.2`

**Comment by gnarf** [comment]
Heads up @mparpaillon - we are getting pretty close to what we would feel comfortable calling a 1.0.0 -- Do you have any more feedback for us / can you take a look at the README on master / the open PR's and help us sanity check for your use cases?
