### ISSUE TITLE
Syntax error in preact-render-spy when running with jest

### ISSUE THREAD

**Issue by conorcussell** [mzgoddard/preact-render-spy#22]
Hi, firstly, looks like an ace library, I was just struggling with enzyme + preact this week!

I've found a potential bug, but it may be that I've not got the correct setup as there doesnt seem to be an issue when running the tests in this repo. 

Running a simple test with Jest gives this error for me, [minimal reproduction here](https://github.com/conorcussell/preact-render-spy-error/blob/master/README.md#preact-render-spy-error)

```
node_modules/preact-render-spy/src/preact-render-spy.js:19
  ),
  ^
SyntaxError: Unexpected token )
```

its fixed by removing the trailing comma after `nodeName` on [this line ](https://github.com/mzgoddard/preact-render-spy/blob/master/src/preact-render-spy.js#L18)

**Comment by gnarf** [comment]
Thanks for the bug report!

@mzgoddard can you try to figure out why the node 6 tests didn't find this error?

Got a patch coming very soon

**Comment by gnarf** [comment]
1.0.0-rc.3 should fix this

**Comment by gnarf** [comment]
Really sorry about this problem! Thanks again for taking a look at the lib and the positive feedback, and an amazing test case all prepared and everything!

#26 should ensure that we never transpile the source files with babel which should ensure travis prevents us from using features of JavaScript that won't be available in Node 6 without transpilation ever again!

**Comment by conorcussell** [comment]
hey absolutely no problem, thanks for making it in the first place and for the quick patch. Have started using it on a project so will let you know how it goes!
