### ISSUE TITLE
Ensure jest isn't transpiling source files (tests only)

### ISSUE THREAD

**Issue by gnarf** [mzgoddard/preact-render-spy#24]
@mzgoddard I think something with using `jest-webpack` on this repo is gonna cause us trouble, in order to maintain better compatibility, do we need it? can we avoid it? jest uses something like babel-register to jsx, do we need something else from `jest-webpack`?

Like I think #22 could maybe have been avoided?

**Comment by mzgoddard** [comment]
In the case of #22 it isn't jest-webpack. It's babel. Babel is trans piling
that trailing comma.  But you can use jest-webpack and jest without babel
which should introduce this problem. We should drop babel-preset-env from
the repo.

**Comment by gnarf** [comment]
We need babel to transpile the tests files if we want jsx, can we set it up
to not transpile the non .test.js files?

**Comment by gnarf** [comment]
Do you know what we need for that? Can you confirm that it would have caught the bug?

**Comment by gnarf** [comment]
I did land https://github.com/mzgoddard/preact-render-spy/commit/d139e7b0a69689fa6f9a87bc7cfe1ff1c5fe66ba so at least eslint will catch this error again, but in case there are other "transpile issues" I'd love to make sure we are only transpiling test source (maybe put tests in a separate directory?)
