### ISSUE TITLE
Consider a TypeScript version/types definition

### ISSUE THREAD

**Issue by gnarf** [mzgoddard/preact-render-spy#27]
Lots of the preact community seems to be using TypeScript, though I'm unfamiliar with how to do it myself, it would be awesome if we could create the type defs needed for those users!

**Comment by Hotell** [comment]
Question is, why is this library not written in typed javascript which can generate those type definitions automatically and thus having 100% contract between lib API and type defs :)

**Comment by gnarf** [comment]
That was the "TypeScript version" part of the issue.  I'd be willing to
work with someone willing to help make that a reality, but for now, the
answer is quite simple: neither of the maintainers know TypeScript 😎

**Comment by gnarf** [comment]
Closed by #30
