### ISSUE TITLE
Issue with `FindWrapper#attr(name)` When `attr` Value is a Boolean

### ISSUE THREAD

**Issue by mendelk** [mzgoddard/preact-render-spy#50]
Say you have a component that has a boolean prop:

```jsx
const Hello = ({ isActive }) => <div style={{ display: isActive ? 'block' : 'none' }}>Hello</div>
<Hello isActive={false} />
```

In such a case, calling `shallow(<Hello isActive={false} />).attr('isActive')` will return `undefined` instead of the `false` you'd expect.

The reason for this is [this line](https://github.com/mzgoddard/preact-render-spy/blob/d803000de26ad85d8b0c5cc3ae3340aad2151804/src/preact-render-spy.js#L207), which checks the truthiness of `item.attributes[name]`, which this case fails, thus returning `undefined`.

Thank you for this wonderful project.

**Comment by gnarf** [comment]
damn... just fixed `null` even but lost `false` :)

I'll get a 1.2.1 out really soon, with a fix.

**Comment by gnarf** [comment]
Oh wait - the `find` works, but the `attr` fetches undefined instead of falsey! -- Will have a PR soon, unless you want to take it on, just add a test case and remove that line! :)

**Comment by gnarf** [comment]
soon meaning tomorrow when I'm working, not the middle of the night :)

**Comment by gnarf** [comment]
In the meantime, you could use `.attrs().isActive`

**Comment by mendelk** [comment]
Wow you're fast @gnarf. I'd have been glad to submit a PR but it looks like you've beaten me to it.

> In the meantime, you could use `.attrs().isActive`

That's exactly what I've done.

**Comment by gnarf** [comment]
v1.2.1 published with bugfix!

**Comment by gnarf** [comment]
Thanks so much for helping us probe the corners and test the edges 😍
