### ISSUE TITLE
Is there any way to simulate keydown events?

### ISSUE THREAD

**Issue by pmcalabrese** [mzgoddard/preact-render-spy#71]
Hi,
I'm trying to write this bit of code in a test

my-test.test.ts
```
...
context.find('.search_input').simulate("keyDown", { keyCode: 65 });
...

```

but the test fail and says:

```

ReferenceError: event is not defined

      at Object.onKeyDown (src/components/search_sale.tsx:199:189)
      at FindWrapper.simulate (node_modules/preact-render-spy/src/preact-render-spy.js:252:31)
      at Object.test (src/components/search_sale.test.tsx:21:35)
          at new Promise (<anonymous>)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

```

Any suggestions what's wrong? Or simpler, how can simulate a KeyDown? I need to fill an input field

Thank you in advance

**Comment by BartWaardenburg** [comment]
Hey @pmcalabrese,

I was just struggling with this as well. What I noticed was that I had an event.preventDefault in my event handler. The event you're passing there doesn't include the preventDefault function.

This is what fixed it for me:

```javascript
input.simulate('keyDown', {
    preventDefault: () => undefined,
    key: 'Escape',
});
```

**Comment by pmcalabrese** [comment]
@BartWaardenburg Thx appreciate your help :)
