### ISSUE TITLE
index.d.ts is missing a number of type signatures

### ISSUE THREAD

**Issue by growlycode** [mzgoddard/preact-render-spy#76]
In index.d.ts, a lot of recent changes have not been applied e.g.

`find<Q, T>(selector: string): FindWrapper<Q, T>;`

should be 

`find<Q, T>(selector: preact.VNode | string): FindWrapper<Q, T>;`

**Comment by gnarf** [comment]
I think we updated most of these, if there are others missing please re-open a PR?
