### ISSUE TITLE
.find by data-attributes

### ISSUE THREAD

**Issue by horprogs** [mzgoddard/preact-render-spy#85]
Hi! First, thank you for your work)

I have a problem, I cannot find by any data-attributes. 
For example:

```
const context = shallow(<SomeComponent />);
console.log(context.find('[data-target="id"]')); // FindWrapper { length: 0 }
```

And .find always return 0 nodes (although this element exist).
I tried different cases: `.find('[data-target="id"]')`, `.find('div[data-target="id"]')`, `.find('data-target="id"')`. But nothing.

Where is my mistake?

**Comment by horprogs** [comment]
I found solution. 
`console.log(context.find(<div data-target="id"/>))`

**Comment by juniorgarcia** [comment]
I'm having a similar problem.

In my case `context.exists('input[type="checkbox"]')` returns true, but  `context.find('input[type="checkbox"]')` returns nothing.

I also realized that if I add a `className` or `id` to the component I want to find, `context.find` returns correctly. I believe that this is a problem with this specific kind of selector when used with `find` function.

**Comment by horprogs** [comment]
Try `context.find(<input type="checkbox" />)`. Maybe it will help you
